### ISSUE TITLE
with-editor fails to fond a suitable emacsclient

### ISSUE THREAD

**Issue by necto** [magit/magit#2492]
Hello,
I have just installed emacs 25.1.50.2 from the official emacs-snapshot PPA for ubuntu 14.04. I also installed spacemacs over it. And there I enabled a git layer. So now it complains on every startup: 

    Warning (with-editor): Cannot determine a suitable Emacsclient

    Determining an Emacsclient executable suitable for the
    current Emacs instance failed.  For more information
    please see https://github.com/magit/magit/wiki/Emacsclient.

my `with-editor-debug` output:

    with-editor: /home/necto/.emacs.d/elpa/with-editor-20160101.32/with-editor.el
    emacs: /usr/bin/emacs (25.1.50.2)
    system:
      system-type: gnu/linux
      system-configuration: x86_64-pc-linux-gnu
      system-configuration-options: --build=x86_64-linux-gnu --prefix=/usr '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' --sysconfdir=/etc --localstatedir=/var '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --sharedstatedir=/var/lib --program-suffix=-snapshot --with-x=yes --with-x-toolkit=gtk3 'CFLAGS=-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security' CPPFLAGS=-D_FORTIFY_SOURCE=2 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro'
    server:
      server-running-p: t
      server-process: #<process server>
      server-use-tcp: nil
      server-name: server
      server-socket-dir: /tmp/emacs1000
        server
      server-auth-dir: ~/.emacs.d/server/
        WARNING: not an accessible directory
    magit-emacsclient-executable:
    value:   nil (nil)
    default: nil (nil)
    funcall: nil (nil)
    path:
      $PATH: "/home/necto/.opam/system/bin:/home/necto/.opam/system/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
      exec-path: (/home/necto/.opam/system/bin/ /home/necto/.opam/system/bin/ /usr/local/sbin/ /usr/local/bin/ /usr/sbin/ /usr/bin/ /sbin/ /bin/ /usr/games/ /usr/local/games/ /usr/lib/x86_64-linux-gnu/emacs/25.1.50/x86_64-linux-gnu/)
      with-editor-emacsclient-path:
        /usr/bin (t)
          /usr/bin/emacsclient (24.3)
          /usr/bin/emacsclient-snapshot (25.1.50)
          /usr/bin/emacsclient.emacs24 (24.3)
        /home/necto/.opam/system/bin/ (t)
        /usr/local/sbin/ (t)
        /usr/local/bin/ (t)
        /usr/sbin/ (t)
        /usr/bin/ (t)
          /usr/bin/emacsclient (24.3)
          /usr/bin/emacsclient-snapshot (25.1.50)
          /usr/bin/emacsclient.emacs24 (24.3)
        /sbin/ (t)
        /bin/ (t)
        /usr/games/ (t)
        /usr/local/games/ (t)
        /usr/lib/x86_64-linux-gnu/emacs/25.1.50/x86_64-linux-gnu/ (t)

I guess the reason is that emacsclient-snapshot proclaims a `25.1.50` while the server is more precise: `25.1.50.2`

**Comment by tarsius** [comment]
That's because the "version suffix" of `/usr/bin/emacsclient-snapshot` was previously unknown to me. I'll add a special case for that.

**Comment by mankoell** [comment]
How to solve this issue? I've the same problem. :crying_cat_face:

**Comment by necto** [comment]
As their page says, I added a workaround into my `.spacemacs` : 

```lisp
  (setq-default with-editor-emacsclient-executable "emacsclient-snapshot")
```

**Comment by tarsius** [comment]
I believe I have fixed this issue (see commit above). Does that not fix the issue for you? Did you update Magit sometime during the last three days?

**Comment by tarsius** [comment]
Nevermind, I think the fix was wrong... checking.

**Comment by mankoell** [comment]
I dont know, I'm just a newb spacemacs user. :baby: :baby_bottle:

**Comment by mankoell** [comment]
I tried to symlink, error message seems to be gone but still have a red powerline.

**Comment by tarsius** [comment]
I've just pushed a fixed fix.

**Comment by sdaaish** [comment]
I have the same problem on Windows 10 for one computer but not on  the other. Use Chocolatey and emacs64 package on both with same version. Have not figured out yet what differs between them. I have tried both melpa and melpa-stable version of magit on the pc that is not working.

My solution is similar, changing the variable to below works.
>         (setq-default with-editor-emacsclient-executable "emacsclient")

The error message:
with-editor: c:/Users/Stig/.emacs.d/elpa/with-editor-20170111.609/with-editor.el
emacs: c:/ProgramData/chocolatey/lib/emacs64/tools/emacs/bin/emacs (25.1.1)
system:
  system-type: windows-nt
  system-configuration: x86_64-w64-mingw32
  system-configuration-options: --prefix=/tmp/emacs --without-imagemagick 'CFLAGS=-O2 -fomit-frame-pointer -g0'
server:
  server-running-p: t
  server-process: #<process server>
  server-use-tcp: t
  server-name: server
  server-socket-dir: nil
    WARNING: not an accessible directory
  server-auth-dir: ~\.emacs.d\server\
    server
magit-emacsclient-executable:
 value:   nil (nil)
 default: nil (nil)
 funcall: nil (nil)
path:
  $PATH: "C:\\tools\\cmdermini\\bin;C:\\tools\\cmdermini\\vendor\\conemu-maximus5\\ConEmu\\Scripts;C:\\tools\\cmdermini\\vendor\\conemu-maximus5;C:\\tools\\cmdermini\\vendor\\conemu-maximus5\\ConEmu;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\OpenSSH-Win64;C:\\Program Files (x86)\\GNU\\GnuPG\\pub;C:\\Program Files (x86)\\GNU\\GnuPG;C:\\Python36\\Scripts\\;C:\\Python36\\;C:\\Program Files\\Broadcom\\Broadcom 802.11 Network Adapter\\Driver;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\NTP\\bin;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\Program Files (x86)\\Toshiba\\Bluetooth Toshiba Stack\\sys\\;C:\\Program Files (x86)\\Toshiba\\Bluetooth Toshiba Stack\\sys\\x64\\;C:\\Program Files (x86)\\Windows Live\\Shared;C:\\HashiCorp\\Vagrant\\bin;C:\\Program Files\\MariaDB 10.1\\bin;C:\\Program Files\\Mercurial;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files\\Git\\cmd;C:\\Users\\Stig\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Stig\\bin;C:\\tools\\cmdermini;C:\\Program Files\\Oracle\\VirtualBox;C:\\Program Files (x86)\\Nmap;C:\\Program Files (x86)\\PuTTY;C:\\Program Files\\Mercurial\\;c:\\local\\bin;;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\share\\vim\\vim74;C:\\tools\\cmdermini\\"
  exec-path: (c:/tools/cmdermini/bin C:/tools/cmdermini/vendor/conemu-maximus5/ConEmu/Scripts C:/tools/cmdermini/vendor/conemu-maximus5 C:/tools/cmdermini/vendor/conemu-maximus5/ConEmu C:/WINDOWS/system32 C:/WINDOWS C:/WINDOWS/System32/Wbem C:/WINDOWS/System32/WindowsPowerShell/v1.0/ C:/ProgramData/chocolatey/bin C:/Program Files/OpenSSH-Win64 C:/Program Files (x86)/GNU/GnuPG/pub C:/Program Files (x86)/GNU/GnuPG C:/Python36/Scripts/ C:/Python36/ C:/Program Files/Broadcom/Broadcom 802.11 Network Adapter/Driver C:/Program Files (x86)/NVIDIA Corporation/PhysX/Common C:/Program Files (x86)/NTP/bin C:/Program Files (x86)/Skype/Phone/ C:/Program Files (x86)/Toshiba/Bluetooth Toshiba Stack/sys/ C:/Program Files (x86)/Toshiba/Bluetooth Toshiba Stack/sys/x64/ C:/Program Files (x86)/Windows Live/Shared C:/HashiCorp/Vagrant/bin C:/Program Files/MariaDB 10.1/bin C:/Program Files/Mercurial C:/ProgramData/Oracle/Java/javapath C:/Program Files/Git/cmd C:/Users/Stig/AppData/Local/Microsoft/WindowsApps C:/Users/Stig/bin C:/tools/cmdermini C:/Program Files/Oracle/VirtualBox C:/Program Files (x86)/Nmap C:/Program Files (x86)/PuTTY C:/Program Files/Mercurial/ c:/local/bin . C:/Program Files/Git/usr/bin C:/Program Files/Git/usr/share/vim/vim74 C:/tools/cmdermini/ c:/ProgramData/chocolatey/lib/emacs64/tools/emacs/libexec/emacs/25.1/x86_64-w64-mingw32)
  with-editor-emacsclient-path:
    c:/ProgramData/chocolatey/lib/emacs64/tools/emacs/bin (t)
      c:/ProgramData/chocolatey/lib/emacs64/tools/emacs/bin/emacsclient.exe (nil)
      c:/ProgramData/chocolatey/lib/emacs64/tools/emacs/bin/emacsclientw.exe (nil)

**Comment by tarsius** [comment]
You do *not* have the same issue. This one was (I fixed it) very specific to Debian and derived GNU/Linux distributions. See https://magit.vc/manual/with-editor/Debugging.html for what to do next. Since it works on one of computers, you should start by running `M-x with-editor-debug` on both computers and comparing the output.

**Comment by sdaaish** [comment]
OK, will try that.

**Comment by rileyrg** [comment]
Just getting this now with emacs 27 built from source and latest magit installed using straight.el
