### ISSUE TITLE
weird slowness

### ISSUE THREAD

**Issue by pvinis** [magit/magit#2552]
im on osx, with git from brew.
magit-version gives `Magit 20160214.1130, Git 2.7.1, Emacs 24.5.1`
in a repo with 800 files, when i have a one line change in one file, `git stage` takes 0.1s
with magit, when i press `s` to stage, it takes a second or so.
i profiled with this
```
(defun profile-mag ()
  (elp-restore-all)
  (elp-instrument-package "magit")
  (elp-reset-all)
  (magit-stage-file "Classes/IKBAppDelegate.m")
  (elp-results))

(profile-mag)
```
and i get this

```
magit-stage-file                                   1           0.60642       0.60642
magit-stage-1                                      1           0.575132      0.575132
magit-run-git                                      1           0.574553      0.574553
magit-process-file                                 68          0.558308      0.0082104117
magit-refresh                                      1           0.466751      0.466751
magit-refresh-buffer                               1           0.434065      0.434065
magit-status-refresh-buffer                        1           0.433637      0.433637
magit-git-str                                      50          0.413999      0.00827998
magit-rev-parse-safe                               33          0.240302      0.0072818787
magit-insert-status-headers                        1           0.164492      0.164492
magit-insert-headers                               1           0.157184      0.157184
magit-insert-head-branch-header                    1           0.157162      0.157162
magit-toplevel                                     5           0.149582      0.0299164
magit-insert-remaining-headers                     1           0.141389      0.141389
magit-git-insert                                   14          0.1406039999  0.0100431428
magit-call-git                                     1           0.107789      0.107789
magit-call-process                                 1           0.099615      0.099615
magit-get                                          14          0.0986100000  0.0070435714
magit-insert-tags-header                           1           0.068757      0.068757
magit-git-string                                   9           0.066705      0.0074116666
magit-git-dir                                      9           0.063822      0.0070913333
magit-get-current-tag                              1           0.059367      0.059367
magit-mode-get-buffers                             2           0.058414      0.029207
magit-process-setup                                1           0.058346      0.058346
magit-get-upstream-branch                          3           0.0570959999  0.0190319999
magit-get-push-branch                              3           0.056162      0.0187206666
magit-insert-upstream-branch-header                1           0.050912      0.050912
magit-get-current-branch                           7           0.05076       0.0072514285
magit-get-push-remote                              3           0.042131      0.0140436666
magit-insert-untracked-files                       1           0.040803      0.040803
magit-insert-unpushed-to-upstream                  1           0.03867       0.03867
magit-insert-unpulled-from-upstream                1           0.038056      0.038056
magit-git-items                                    1           0.033923      0.033923
magit-mode-get-buffer                              1           0.031635      0.031635
magit-process-finish                               1           0.029698      0.029698
magit-process-unset-mode-line                      1           0.029599      0.029599
magit-process-buffer                               1           0.029298      0.029298
magit-process-set-mode-line                        1           0.028881      0.028881
magit-git-exit-code                                3           0.027899      0.0092996666
magit-insert-push-branch-header                    1           0.021682      0.021682
magit-bisect-in-progress-p                         3           0.021636      0.007212
magit-rev-verify                                   3           0.021383      0.0071276666
magit-insert-unpulled-from-pushremote              1           0.021138      0.021138
magit-insert-unpushed-to-pushremote                1           0.020897      0.020897
magit-rev-format                                   2           0.016044      0.008022
magit-git-success                                  2           0.0149810000  0.0074905000
magit-insert-rebase-sequence                       1           0.014254      0.014254
magit-rebase-in-progress-p                         1           0.014245      0.014245
magit-insert-sequencer-sequence                    1           0.014211      0.014211
magit-insert-unstaged-changes                      1           0.013963      0.013963
magit-insert-staged-changes                        1           0.011105      0.011105
magit-git-wash                                     4           0.01094       0.002735
magit-get-next-tag                                 1           0.009184      0.009184
magit-maybe-save-repository-buffers                2           0.00814       0.00407
magit-save-repository-buffers                      1           0.008127      0.008127
magit-insert-bisect-log                            1           0.007294      0.007294
magit-insert-bisect-output                         1           0.007187      0.007187
magit-revert-in-progress-p                         1           0.007185      0.007185
magit-insert-bisect-rest                           1           0.007176      0.007176
magit-get-boolean                                  1           0.007093      0.007093
magit-git-true                                     1           0.007083      0.007083
magit-insert-merge-log                             1           0.007072      0.007072
magit-cherry-pick-in-progress-p                    1           0.007011      0.007011
magit-insert-stashes                               1           0.006991      0.006991
magit-insert-am-sequence                           1           0.00697       0.00697
magit-am-in-progress-p                             1           0.006963      0.006963
magit-auto-revert-buffers                          1           0.001008      0.001008
magit-wash-sequence                                2           0.000657      0.0003285
magit--safe-default-directory                      14          0.000584      4.171...e-05
magit-turn-on-auto-revert-mode-if-desired          1           0.000553      0.000553
magit-diff-wash-diffs                              1           0.000531      0.000531
magit-diff-wash-diff                               1           0.00046       0.00046
magit-process-git-arguments                        68          0.0003710000  5.455...e-06
magit-diff-insert-file-section                     1           0.000277      0.000277
magit-expand-git-file-name                         19          0.0002230000  1.173...e-05
magit-section-set-visibility-from-cache            12          0.0002070000  1.725...e-05
magit-insert-heading                               9           0.000187      2.077...e-05
magit-diff-wash-hunk                               2           0.000183      9.15e-05
magit-section-show                                 5           0.000152      3.04e-05
magit-process-insert-section                       1           0.00014       0.00014
magit-section-visibility-ident                     17          0.0001389999  8.176...e-06
magit-section-ident                                31          0.000125      4.032...e-06
magit-insert-child-count                           9           7.599...e-05  8.444...e-06
magit-section-update-highlight                     1           6.4e-05       6.4e-05
magit-cygwin-env-vars                              68          6.099...e-05  8.970...e-07
magit-format-status-tag-sentence                   1           5.4e-05       5.4e-05
magit-get-section                                  11          3.9e-05       3.545...e-06
magit-file-lines                                   1           3e-05         3e-05
magit-diff-highlight                               1           2.9e-05       2.9e-05
magit-delete-line                                  6           2.7e-05       4.5e-06
magit-section-goto-successor                       1           2.5e-05       2.5e-05
magit-section-update-visibility-cache              5           2.499...e-05  4.999...e-06
magit-diff-expansion-threshold                     12          1.500...e-05  1.25e-06
magit-section-match                                1           1.2e-05       1.2e-05
magit-refresh-get-relative-position                1           1e-05         1e-05
magit-diff-scope                                   1           9e-06         9e-06
magit-section-highlight                            1           9e-06         9e-06
magit-run-hook-with-benchmark                      2           6e-06         3e-06
magit-section-hide                                 1           6e-06         6e-06
magit-current-section                              4           4.999...e-06  1.249...e-06
magit-section-make-overlay                         1           4e-06         4e-06
magit-diff-type                                    1           4e-06         4e-06
magit-process-truncate-log                         1           3e-06         3e-06
magit-insert-diff-filter-header                    1           3e-06         3e-06
magit-region-sections                              1           2e-06         2e-06
magit-decode-git-path                              2           2e-06         1e-06
magit-wip-commit-after-apply                       1           1e-06         1e-06
magit-section-match-1                              1           1e-06         1e-06
magit-wip-commit-before-change                     1           1e-06         1e-06
magit-insert-error-header                          1           0.0           0.0
magit-insert-log                                   2           0.0           0.0
magit-cancel-section                               3           0.0           0.0
```

is that normal? that's slow, right?

**Comment by warner** [comment]
I noticed something similar after updating today (OS-X, git-2.7.1 from homebrew, magit-20160214.1130 from elpa/melpa). The very first 'C-x g' in a repo after startup took 9 seconds (during which time emacs was unresponsive). I haven't been able to gather much more information (like whether git was running that entire time), but usually this runs so fast that I never notice it. Subsequent 'g' updates in that same repo take less than half a second.

If there are no obvious smoking guns in the recent changes, I could try to bisect this down a bit.

**Comment by warner** [comment]
Oh, here's a useful datapoint: Using `C-u C-x g` (i.e. `magit-status` but read the repo directory from the minibuffer) takes that same 9 seconds before it even asks me what directory to use. Doing `M-x load-library magit RET` in a new emacs also takes 9 seconds. So for me, at least, this is either something happening during autoload (maybe my byte-compiled files are unusable? I don't see anything in `*Messages*` about it), or magit is running something at load time that's taking a surprisingly long amount of time.

**Comment by danrharms** [comment]
Just a hunch, but try disabling magic-auto-revert-mode. I experienced a similar slowdown yesterday due to this mode. There was some sort of recursion going on, I haven't been able to investigate more.

**Comment by npostavs** [comment]
> Doing `M-x load-library magit RET` in a new emacs also takes 9 seconds.

That sounds like http://magit.vc/manual/magit/Emacs-245-hangs-when-loading-Magit.html, but not the same as what OP reported.

**Comment by ReneFroger** [comment]
This might be related: https://github.com/magit/magit/issues/1907#issuecomment-117228330

Could you bisecting your Emacs config?

**Comment by pvinis** [comment]
i dont have that enabled..

-- 
Pavlos Vinieratos

**Comment by ilohmar** [comment]
Had a similar experience.  Even when you have `magit-auto-revert-mode` turned off after loading magit, it's on by default, causing the super-slow loading when many git-controlled files are open.  ```(setq magit-auto-revert-mode nil)``` unconditionally in your startup file should fix that (if you're not using the mode, of course), so that the variable is nil *while magit is loading*.

**Comment by warner** [comment]
Yeah, that was it. I tried the following function to temporarily disable the mode, just while loading, then put it back to whatever it was before:

```elisp
(defun my-load-magit ()
  (interactive)
  (let ((magit-auto-revert-mode nil)
        (start (float-time)))
    (load-library "magit")
    (message "elapsed: %f" (- (float-time) start))
    ))
```

Calling this (right after startup and calling any magit functions) takes about 0.5 seconds. Restarting emacs and calling again with `t` instead of `nil` takes 11 seconds. I have about 240 buffers open at startup (via desktop-save-mode), most of which are probably under git control, which implies something in eval is taking about 40ms per buffer.

I guess the easiest workaround is to force-load magit (with a function like above) from my `emacs.el` at startup. I use magit every day, so it's not like I'm saving any time or memory by deferring to an autoload.

A better fix would be to somehow rig the autoload function to change `magit-auto-revert-mode` before and after loading.. can the autoloader call a function instead of loading the library directly?

The best fix would be to isolate where in magit this delay is coming from and wrap *that*. It's happening at eval time, which should narrow down the possible location somewhat. If we're right and this really is a recent issue, then bisecting the magit history might be a quick way to narrow it down.

**Comment by warner** [comment]
I opened a separate ticket for the auto-revert slowness, since it looks like a distinct issue. Sorry @pvinis for hijacking your bug! Please now return to your regularly-scheduled git-stage slowness issue :).

**Comment by pvinis** [comment]
no problem :) i was confused because i was trying the things you said, but nothing changed for me. its still taking 1 sec, and the profiling is still the same.

**Comment by npostavs** [comment]
> git stage takes 0.1s
> with magit, when i press s to stage, it takes a second or so.

From your profiling info, it's taking 0.6s, most of the time in `magit-refresh` (note that `magit-stage` is more like `git stage ; git status`, then just a plain `git stage`). You can speed up `magit-refresh` by removing things from `magit-status-sections-hook` (see also http://magit.vc/manual/magit/Performance.html, and https://emacs.stackexchange.com/questions/19440/magit-extremely-slow-in-windows-how-do-i-optimize/19525#19525 for a minimalist status screen that should be much faster).

There were some reports of magit being slower on "El-Capitan" (that's an OSX version right?) https://github.com/magit/magit/issues/2104#issuecomment-164234649

**Comment by tarsius** [comment]
There also have been reports of homebrew's `emacs-mac` being slower than its `emacs`.

**Comment by pvinis** [comment]
i am using emacs. not emacs-mac

**Comment by tarsius** [comment]
Does https://github.com/magit/magit/compare/jb/cache?expand=1 help enough?

**Comment by pvinis** [comment]
how do i install/use this?

**Comment by tarsius** [comment]
http://magit.vc/manual/magit/Installing-from-the-Git-repository.html

**Comment by pvinis** [comment]
it is faster. not amazingly faster, but the difference is definitely noticeable.

I investigated a bit more. Here is what i found.
jb/cache alone is the fastest.
master alone is very close to jb/cache perf.
latest in melpa alone is same as master.
latest in melpa, but also many packages in the elpa dir, it gets super slow..
that shouldnt happen right? or should it?
the initial info i posted in the beginning here are with the latter config.
then i tried jb/cache with that last configuration, (many other packages) and it was somewhere on the same perf as master alone. so i guess jb/cache makes things faster in general.

**Comment by tarsius** [comment]
I've just pushed 230ab992fbbb6d0dbb7164ce87d64834c5276719.

Beyond that I cannot do anything about this at this point - I am trying to take a break. Ultimately we'll need to use libgit to address this. See #2539.

**Comment by npostavs** [comment]
> I've just pushed 230ab99.

I suppose the relevant commit is 2a37ad56a87f830ddac80415cb6be3067514d94c
