### ISSUE TITLE
[w32] Interactive rebasing doesn't work with non-cmd shell-file-name

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#2794]
For a long time (possibly forever) I had a problem using interactive rebasing from magit.  Today I had updated magit and tried to dig into it.

Disclaimer: It was hard to find it, and I'm not sure that I got to the right place, and it might be something with my own environment.  Also, I found it in `with-editor` and the readme file there said to post issues here...

The place where I tracked it to is the place where `with-editor` does this:

    (shell-quote-argument with-editor-emacsclient-executable)

This gets a path that starts with "c:/" and since I'm using cygwin, that returns

    "c\\:/Program\\ Files/Emacs/bin/emacsclient.exe"

and that eventually leads to a failure when running the command which produces this error message (the line number in the error is probably a bit off since I added some printouts to debug that too):

    /mingw64/libexec/git-core/git-rebase--interactive: line 262: c;C:UserselbarzilAppDataLocalProgramsGitProgram FilesEmacsbinemacsclient.exe: command not found
    Could not execute editor

That's as much as I found.  To see if I can hack around it I replaced the shell quoting thing with:

      (push (concat with-editor--envvar "=\"" with-editor-emacsclient-executable
                    (and ...same...)
                    "\"")
            process-environment)

and that made it work.  Is this some known problem?  Any ideas what could the problem be or how I can debug it further?

---

`magit-version` says:

    Magit 2.8.0-28-g0ad041c, Git 2.10.0.windows.1, Emacs 24.5.1, windows-nt

`with-editor-debug` says:

    with-editor: c:/eli/.emacs.d/elpa/with-editor-20160408.201/with-editor.el
    emacs: c:/Program Files/Emacs/bin/emacs (24.5.1)
    system:
      system-type: windows-nt
      system-configuration: i686-pc-mingw32
      system-configuration-options: --prefix=/c/usr --host=i686-pc-mingw32
    server:
      server-running-p: t
      server-process: #<process server>
      server-use-tcp: t
      server-name: server
      server-socket-dir: nil
        WARNING: not an accessible directory
      server-auth-dir: ~/.emacs.d/server/
        server
    magit-emacsclient-executable:
     value:   c:/Program Files/Emacs/bin/emacsclient.exe (24.5)
     default: c:/Program Files/Emacs/bin/emacsclient.exe (24.5)
     funcall: c:/Program Files/Emacs/bin/emacsclient.exe (24.5)
    path:
      $PATH: "...ellided..."
      exec-path: (...ellided...)
      with-editor-emacsclient-path:
        c:/Program Files/Emacs/bin (t)
          c:/Program Files/Emacs/bin/emacsclient.exe (24.5)
          c:/Program Files/Emacs/bin/emacsclientw.exe (nil)
        C:/bin (t)
        ...ellided...
        C:/Users/elbarzil/AppData/Local/Programs/Git/cmd (t)
        C:/Program Files/nodejs/ (t)
        C:/windows/system32 (t)
        C:/windows (t)
        C:/windows/System32/Wbem (t)
        ...ellided...
        c:/Program Files/Emacs/libexec/emacs/24.5/i686-pc-mingw32 (t)
        c:/cygwin/bin (t)

**Comment by johnmastro** [comment]
I also use a native Windows Emacs with Cygwin and ran into similar errors in a variety of contexts. I don't remember if your particular error was one that I experienced, but some time ago I added this to my init file:

```emacs-lisp
(defun maybe-cygwinize-file-name (file)
  "Convert a Windows file name from Emacs-style to Cygwin-style.
Assume a cygdrive path prefix of \"/\" - \"c:/foo\" becomes
\"/foo\" and \"d:/foo\" becomes \"/d/foo\"."
  (if (and file (string-match "\\`\\([A-Za-z]\\):\\(/.*\\)" file))
      (let ((drive (match-string 1 file))
            (name (match-string 2 file)))
        (if (member drive '("c" "C"))
            name
          (concat "/" drive name)))
    file))

(defun cygwin-shell-quote-argument (args)
  (list (maybe-cygwinize-file-name (car args))))

(when (eq system-type 'windows-nt)
  (advice-add 'shell-quote-argument :filter-args
              #'cygwin-shell-quote-argument))
```

Admittedly it's a bit extreme, and I'm not suggesting you (much less Magit) adopt it, just offering it as food for thought.

**Comment by tarsius** [comment]
Magit also contains some code that tries to deal with the strange things that happen when using windows-nt Emacs with cygwin Git. Cygwin's path handling is extremely obscure and a source of great pain. It's handling of globbing is equally frustrating.

Try if any of the following work:

```lisp
(setq with-editor-emacsclient-executable
      (magit-expand-git-file-name
       (substring (with-editor-locate-emacsclient) 2)))

(setq with-editor-emacsclient-executable
      (magit-expand-git-file-name
       (with-editor-locate-emacsclient)))

(setq with-editor-emacsclient-executable
      (magit-convert-git-filename
       (with-editor-locate-emacsclient)))
```

Please also post the values returned by these three forms as well as that returned by just `(with-editor-locate-emacsclient)`.

**Comment by johnmastro** [comment]
> Magit also contains some code that tries to deal with the strange things that happen when using windows-nt Emacs with cygwin Git. Cygwin's path handling is extremely obscure and a source of great pain. It's handling of globbing is equally frustrating.

Indeed. And to clarify, one reason I ended up advicing `shell-quote-argument` directly is that I experienced errors like this from several packages that interact with shell commands, not just Magit, which already does quite a bit to accommodate Cygwin.

**Comment by tarsius** [comment]
Maybe someone(tm) should factor out all the hacks that can be found in Magit into a separate package. But that won't by any fun at all, so it is no surprise nobody has done so already. That library should then be extensively commented because the things it does it does out of necessity only, they make no sense whatsoever if you don't know why they are needed. Maybe I will compile a list of past discussions in issues and commit messages at some point in the future.

**Comment by npostavs** [comment]
> [...]since I'm using cygwin[...]
> Magit 2.8.0-28-g0ad041c, Git 2.10.0.windows.1, Emacs 24.5.1, windows-nt

If I understand correctly, you are using Windows git and Emacs, but setting `shell-name` to a cygwin shell. Therefore `shell-quote-argument` quotes things to protect from bourne-shell style expansion, but this is incorrect for git commands (not exactly sure where it goes wrong, but evidently it does). So let-binding `shell-name` to the correct thing for git should probably fix it:

```elisp
       ;; Tell $EDITOR to use the Emacsclient.
       (let ((shell-name "cmdproxy")) ; Git for Windows expects `w32-shell-dos-semantics' quoting
         (push (concat with-editor--envvar "="
                       (shell-quote-argument with-editor-emacsclient-executable)
```

Recognizing this situation and only doing it when needed could be tricky though.

**Comment by Lotbert** [comment]
i think this could help:
> It seems very usual for emacs users on w32 to use cygwin or mingw.
Right now shell-quote-argument would return something wrong when bash
or some "intelligent" shell is used on w32 because it assumes a dumb
w32 shell.
http://emacs-devel.gnu.narkive.com/WoVVXqWq/should-shell-quote-argument-really-use-eq-system-type-windows-nt

**Comment by npostavs** [comment]
> Right now shell-quote-argument would return something wrong when bash
> or some "intelligent" shell is used on w32 because it assumes a dumb
> w32 shell.

This is no longer the case. Something like the patch in that thread was applied. Now the problem is sort of the opposite: `shell-quote-argument` is wrong because OP is using bash, except that Git for Windows doesn't use bash and rather expects the "dumb" w32 style quoting.

**Comment by elibarzilay** [comment]
@johnmastro: I tried that, but it doesn't work.  The quoting itself works fine, but the error becomes

    /mingw64/libexec/git-core/git-rebase--interactive: line 258: C:/Program/: No such file or directory

That's why I hesitated to go with such hacks -- it looks like there's something else on the way that tries to do some "smart" fixing, and that gets messed up when there are backslashes.  In my original case it leads to that weird thing, and with your hack it breaks on the backslashed space.  I know that magit is trying to go around some of the weirness, and trying to do the above might mess things further...

@npostavs: yes, my usual shell is from cygwin, which makes shell-quote-argument usually do the right thing.  I thought that this is a result of git-for-windows comes with its on msys environment, but it doesn't look like that's the case.  Trying to force the shell to be bad is an interesting idea, but finding where to do it will indeed be tricky...

**Comment by elibarzilay** [comment]
@tarsius: before any changes I get

    (with-editor-locate-emacsclient)
    => "c:/Program Files/Emacs/bin/emacsclient.exe"
    with-editor-emacsclient-executable
    => "c:/Program Files/Emacs/bin/emacsclient.exe"
    (magit-expand-git-file-name (substring (with-editor-locate-emacsclient) 2))
    => "/Program Files/Emacs/bin/emacsclient.exe"
    (magit-expand-git-file-name (with-editor-locate-emacsclient))
    => "c:/Program Files/Emacs/bin/emacsclient.exe"
    (magit-convert-git-filename (with-editor-locate-emacsclient))
    => "c:/Program Files/Emacs/bin/emacsclient.exe"

I then tried the only different value in the above:

    (setq with-editor-emacsclient-executable
          "/Program Files/Emacs/bin/emacsclient.exe")

and the result is similar to what I got with @johnmastro's hack:

    /mingw64/libexec/git-core/git-rebase--interactive: line 258: C:/Users/elbarzil/AppData/Local/Programs/Git/Program/: No such file or directory

BTW, I did end up finding a hack to go around it: I explicitly set the variable to just an executable name that is now on my PATH:

    (setq with-editor-emacsclient-executable "emacsclient")

and that works, but just because it avoids any quoting...

**Comment by npostavs** [comment]
> yes, my usual shell is from cygwin, which makes shell-quote-argument usually do the right thing. I thought that this is a result of git-for-windows comes with its on msys environment, but it doesn't look like that's the case. Trying to force the shell to be bad is an interesting idea, but finding where to do it will indeed be tricky...

I'm quite sure that let-binding `shell-name` around `(concat with-editor--envvar...` should fix the problem for you (although I've not tested yet). The tricky part is not about *where* to do it, the tricky part is deciding *whether* do to it at all (for other users).

**Comment by elibarzilay** [comment]
Yes, I got that -- I just hesitate to even try it since it's hacking the `with-editor` tool so it won't be sustainable if it's just my own hack.  If anyone who's in charge of `with-editor` wants me to try it, I'll be happy to...  (Are you?)

**Comment by npostavs** [comment]
Oh, well, as with magit tarsius is the lead maintainer but I've basically taken the lead on Windows/cygwin/msys related stuff (since tarsius doesn't run Windows). So yes, it would be useful if you could confirm that the `shell-file-name` hack works (by the way I misnamed it as `shell-name` above, will edit).

Then we have to think about how to detect whether it's needed. I think `(and (eq system-type 'windows-nt) (not magit-cygwin-mount-points))` should be the correct condition. Since the decision is specific to with-editor's caller, we'll need some kind of interface in with-editor so callers (like magit) can say what kind of shell quoting is wanted.

**Comment by kimgronqvist** [comment]
I might have missed something, but is it really only Cygwin specific? I don't use Cygwin and still get this with Emacs 25.1 and Windows 10:

```js
  1 C:/Program Files/Git/mingw64/libexec/git-core/git … rebase -i 0632866^
/mingw64/libexec/git-core/git-rebase--interactive: line 258: c;C:Program: command not found
Could not execute editor
```

I'm not really sure what it's trying to run, since I don't even have emacsclient in any Program-folder.

```
with-editor-emacsclient-executable is a variable defined in ‘with-editor.el’.
Its value is "c:/home/bin/emacs25/bin/emacsclient.exe"
```

**Comment by npostavs** [comment]
> I might have missed something, but is it really only Cygwin specific? I don't use Cygwin and still get this with Emacs 25.1 and Windows 10:

I believe it depends on your value of `shell-file-name`, please post it.

> I'm not really sure what it's trying to run, since I don't even have emacsclient in any Program-folder.

Looks like path translation (Git for Windows uses Msys internally), notice that `c:` was changed into `c;`.

**Comment by kimgronqvist** [comment]
```
shell-file-name is a variable defined in ‘C source code’.
Its value is "C:/Program Files/Git/bin/sh.exe"
```

I have Msys setup as my Emacs shell. This is my shell config:

``` elisp
(when window-system
  (setq explicit-shell-file-name "C:/Program Files/Git/bin/sh.exe")
  (setq shell-file-name explicit-shell-file-name)
  (setq explicit-sh.exe-args '("--login" "-i"))
  (setenv "SHELL" shell-file-name)
  (add-to-list 'exec-path "C:/Program Files/Git/bin")
  (add-hook 'comint-output-filter-functions 'comint-strip-ctrl-m))
```

**Comment by npostavs** [comment]
> I have Msys setup as my Emacs shell.

Yeah, same issue: choosing a `shell-file-name` that gives `(w32-shell-dos-semantics) => nil`.

**Comment by tarsius** [comment]
@elibarzilay have you tried @npostavs suggestion now?

@npostavs I would like to get this into the next release, but I don't think I can be of much help here. Is there anything I can do? (And of course if you are just to busy right now, then that is perfectly okay.)

**Comment by npostavs** [comment]
Actually, I suppose just doing 
```elisp
  (let ((shell-file-name (if (and (eq system-type 'windows-nt) (not magit-cygwin-mount-points))
                             "cmdproxy" shell-file-name)))
    (with-editor "GIT_EDITOR"
...
```

around every `with-editor` call would work. @tarsius any thoughts on whether/how to abstract this?

**Comment by tarsius** [comment]
If it's around *every* call, why not just move it *inside*?

`magit-cygwin-mount-points` and related code would have to be renamed and moved, but that doesn't seem like such a big deal.

**Comment by tarsius** [comment]
Hm. It uses `(process-lines magit-git-executable "--exec-path")` and we of course cannot use that if we don't know whether `git` is available. Maybe provide a `magit-with-editor` wrapper?

**Comment by tarsius** [comment]
And that's just how we figure out if `git` comes in the cygwin flavor...
So yeah, a `magit-with-editor` is probably the best we can do.

**Comment by elibarzilay** [comment]
@tarsius, @npostavs: sorry that I couldn't get to try it earlier, but I just updated and I can confirm that it works fine for me now -- thanks!

BTW, compilation failed because of updates to `with-editor`: the missing variable name looked promising, and indeed, after updating it one of the things that annoyed me is resolved now: the fact that it'd leave me with some `.git/whatever` after editing a commit message etc.  So thanks for that too!

**Comment by dgchurchill** [comment]
I hit this same issue even though my `shell-file-name` was already set to cmdproxy. Turned out my issue was that neither `cmdproxy` nor `cmdproxy.exe` were listed in `w32-system-shells`.

**Comment by npostavs** [comment]
> Turned out my issue was that neither `cmdproxy` nor `cmdproxy.exe` were listed in `w32-system-shells`.

That is normal, and it should not matter: `w32-shell-dos-semantics` explicitly checks for `cmdproxy` or `cmdproxy.exe`. I guess you've changed `COMSPEC` then?

```elisp
(defun w32-shell-dos-semantics ()
  "Return non-nil if the interactive shell being used expects MS-DOS shell semantics."
  (or (w32-system-shell-p (w32-shell-name))
      (and (member (downcase (file-name-nondirectory (w32-shell-name)))
		   '("cmdproxy" "cmdproxy.exe"))
	   (w32-system-shell-p (getenv "COMSPEC")))))
```

**Comment by dgchurchill** [comment]
Ah apologies, I didn't read far enough into `w32-shell-dos-semantics`. Turns out that `COMSPEC` is not set at all. Only seems to be set for me in a `cmd.exe` shell and not in any other process. If I set `COMSPEC` in my Emacs session then everything works correctly without modifying `w32-system-shells`. Thanks :)

**Comment by npostavs** [comment]
> Turns out that `COMSPEC` is not set at all.

Huh. How did you manage that one?

**Comment by dgchurchill** [comment]
No idea really. I possibly just deleted it accidentally while modifying other system environment variables in the Environment Variables dialog. I don't remember changing anything there recently though and interactive rebase in Magit only broke recently for me.
