### ISSUE TITLE
Error in process sentinel when cancelling interactive rebase when using linum-mode

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2805]
Recipe (it's a little odd):

`emacs -Q`
`M-x package-initialize RET` (it has to use this instead of manual loading, and the error is triggered even when only magit and its dependencies are installed)
`M-x linum-mode RET`
`M-x magit-status RET` and choose a suitable repo
`C-x 1`
Start an interactive rebase and choose a commit to rebase onto.
`M-: (switch-to-buffer "*scratch*")`
`M-: (switch-to-buffer "git-rebase-todo")`
`C-c C-k`

The error shows up in both 24.5 and 25.1. Taking out the `linum-mode` or `C-x 1` avoids the error somehow.

Here's a backtrace:

```elisp
Debugger entered--Lisp error: (user-error "Not inside a Git repository")
  signal(user-error ("Not inside a Git repository"))
  user-error("Not inside a Git repository")
  magit-mode-get-buffer(magit-status-mode)
  magit-process-finish(#<process git>)
  magit-process-sentinel(#<process git> "exited abnormally with code 1\n")
  magit-sequencer-process-sentinel(#<process git> "exited abnormally with code 1\n")
  delete-process(#<process server5715 <4>>)
  with-editor-return(t)
  with-editor-cancel(nil)
  funcall-interactively(with-editor-cancel nil)
  call-interactively(with-editor-cancel nil nil)
  command-execute(with-editor-cancel)
```

`Magit 20160926.517, Git 2.9.3, Emacs 25.1.3, gnu/linux`

**Comment by tarsius** [comment]
> `M-: (switch-to-buffer "git-rebase-todo")`
> `C-c C-k`

Something appears to have previously changed the value of `default-directory`. Confirm the value before you press `C-c C-k`. Once we actually know the value is wrong we can start investigating why that is the case.

**Comment by fice-t** [comment]
The value of `default-directory` is the same (`<repo>/.git/rebase-merge/`) both before and after `switch-to-buffer`.

However, if I do `e default-directory` on the backtrace, then the `default-directory` is `~/`.

More info: `magit-mode-get-buffer` is being called when the current buffer is `*scratch*`, but only when `*scratch*` has `linum-mode` on.

**Comment by fice-t** [comment]
`emacs -Q  --debug-init --eval "(setq debug-on-error t)" -L .emacs.d/elpa/dash-20160820.501 -L .emacs.d/elpa/git-commit-20160929.801 -L .emacs.d/elpa/magit-popup-20160821.1338 -L .emacs.d/elpa/with-editor-20160929.1143 -L . -L .emacs.d/elpa/magit-20160930.515`

I got it to reproduce using the above loading and without `package-initialize`. For whatever reason the loading in the issue template doesn't produce the error.

**Comment by npostavs** [comment]
`linum-mode` uses an idle timer, that's probably related somehow.

**Comment by tarsius** [comment]
> `linum-mode` uses an idle timer, that's probably related somehow.

Probably yes, but I don't see anything in `magit-process-sentinel` or `magit-process-filter` that would give an idle timer the opportunity to run. Before these functions run yes, but once they run they make the correct buffer with the correct `default-directory` current, and no idle timer should be able to mess with those things. But maybe I miss something and something that they call gives a timer the opportunity to do so.

**Comment by tarsius** [comment]
`linum-mode` also uses a bunch of hooks. Maybe one of those kicks in a bad moment. I suppose we could protect against that, but it seems `linum-mode` should be the one that ensures, that it does not mess with what buffer/window is current/selected if it runs at times when this could affect other code.

**Comment by tarsius** [comment]
I think that if we cannot come up with more precise steps to reproduce, which do not include steps that seem entirely unrelated to the issue at hand, then we will have a very hard time figuring out what is going on. I.e. the only way to do so would be require reading lots of very low-level code, in the command-loop and such.

**Comment by tarsius** [comment]
Maybe give `nlinum-mode` a change? ;-)

**Comment by tarsius** [comment]
A bunch of low-level issues have bubbled up lately.  This one seems like the least severe (and most obscure)  so I probably won't dig into it any time soon. It's also strange that nobody had this issue before, `linum-mode` isn't exactly an obscure mode.

**Comment by fice-t** [comment]
> I think that if we cannot come up with more precise steps to reproduce, which do not include steps that seem entirely unrelated to the issue at hand

If it helps, I found out that executing this (after loading `linum-mode`) in the scratch buffer:

```elisp
(progn (remove-hook 'window-scroll-functions 'linum-after-scroll t)
       (remove-hook 'window-configuration-change-hook 'linum-update-current t))
```

Avoids the error.

> Maybe give `nlinum-mode` a change? ;-)

Oh, I should have mentioned that I actually produced this with `nlinum-mode` initially, but I mentioned `linum-mode` since it's built-in.

**Comment by fice-t** [comment]
@tarsius 
> which do not include steps that seem entirely unrelated to the issue at hand

I've knocked off the two odd things to give you the following odd thing:
```elisp
(progn (require 'magit)
       (add-hook 'window-configuration-change-hook (lambda () (font-info (face-font 'magit-branch-local))) nil t))
```

The above should be enough for you to reproduce it. Though make sure to open Emacs outside of a git repository (that messes up reproduction).

**Comment by tarsius** [comment]
> I've knocked off the odd steps to give you the following odd step:

Thanks ;-) That narrows things down a lot. I'll try to have another look soon.

**Comment by tarsius** [comment]
Okay I was able to reproduce, though not consistently, there appear other factors that contribute to when the bug kicks in. I couldn't figure out why the wrong buffer was current when the sentinel was running, but that isn't really the issue anyway.

There are all kinds of reasons why some unexpected buffer might be current, and we have to cope with that. I found two instances in sentinel related code, where we don't properly ensure that we are inside an appropriate buffer before calling functions that expect that we are. These are fixed now.

Thanks for bringing this to my attention!

**Comment by fice-t** [comment]
@tarsius Thanks, it doesn't error for me anymore.

Though when following the bug recipe and after canceling the rebase, the `git rebase` is still present in the mode line. Normally that is wiped out after canceling the rebase.

**Comment by fice-t** [comment]
@tarsius The below patch fixes the above. Does it make sense to do this?

```patch
diff --git a/lisp/magit-process.el b/lisp/magit-process.el
index 1f9ca41..6f14664 100644
--- a/lisp/magit-process.el
+++ b/lisp/magit-process.el
@@ -791,7 +791,8 @@ as argument."
           default-dir (process-get arg 'default-dir)
           section     (process-get arg 'section)
           arg         (process-exit-status arg)))
-  (magit-process-unset-mode-line)
+  (with-current-buffer command-buf
+    (magit-process-unset-mode-line))
   (when (featurep 'dired)
     (dired-uncache default-dir))
   (when (buffer-live-p process-buf)
```

**Comment by tarsius** [comment]
Thanks! I've applied that fix.

**Comment by tarsius** [comment]
Err, it was a rather stupid mistake in that last commit. I've pushed a fix.

**Comment by fice-t** [comment]
That fixes the modeline issue, thanks.

Though it still does error for me. It seems like that commit is calling `magit-mode-get-buffer` inside `process-buf` instead of `command-buf` like it did before.

**Comment by tarsius** [comment]
> Though it still does error for me.

You get "Not inside a Git repository" again?

> calling `magit-mode-get-buffer` inside `process-buf` instead of `command-buf` like it did before.

That's intentional, the former is more likely to exist and their `default-directory` should be the same and that's all that should matters to `(magit-mode-get-buffer 'magit-status-mode)`.

**Comment by fice-t** [comment]
> You get "Not inside a Git repository" again?

Yep.

> That's intentional, the former is more likely to exist and their default-directory should be the same and that's all that should matters to (magit-mode-get-buffer 'magit-status-mode).

Ah, okay. I did try changing the function to use `'command-buf` again, but it still errors. I'm not sure what's wrong now.

**Comment by fice-t** [comment]
> I'm not sure what's wrong now.

Actually, yes I do. In 9986334 a `with-current-buffer` was dropped at the end of `magit-process-finish`. I was confused since the backtrace for whatever reason indicated that `magit-sequencer-process-sentinel` was the culprit.

**Comment by tarsius** [comment]
Yes, that was the "stupid mistake" I mentioned above. In c3a3c5239d89af6c229ec97bd592306cd1d33aa7 I then moved it into another `with-current-buffer`.

**Comment by tarsius** [comment]
...ah at the *end*. Indeed.

**Comment by tarsius** [comment]
And fixed too. Sorry about the mess I have created here.

**Comment by fice-t** [comment]
No problem, thanks for fixing it.
