### ISSUE TITLE
Cannot read tree refs/wip/wtree/refs/heads/master

### ISSUE THREAD

**Issue by michael-heerdegen** [magit/magit#4037]
Hi,
I'm having magit-wip-after-save-mode turned on in my config all the time (for years).  Since some weeks or so this is broken for me - here is a backtrace:

```
Debugger entered--Lisp error: (error "Cannot read tree refs/wip/wtree/refs/heads/master")
  signal(error ("Cannot read tree refs/wip/wtree/refs/heads/master"))
  error("Cannot read tree %s" "refs/wip/wtree/refs/heads/master")
  (or (magit-git-success "read-tree" "--reset" it (concat "--index-output=" #:file4)) (error "Cannot read tree %s" it))
  (progn (or (magit-git-success "read-tree" "--reset" it (concat "--index-output=" #:file4)) (error "Cannot read tree %s" it)))
  (if it (progn (or (magit-git-success "read-tree" "--reset" it (concat "--index-output=" #:file4)) (error "Cannot read tree %s" it))))
  (let ((it parent)) (if it (progn (or (magit-git-success "read-tree" "--reset" it (concat "--index-output=" #:file4)) (error "Cannot read tree %s" it)))))
  (let ((default-directory #:toplevel5)) (let ((it parent)) (if it (progn (or (magit-git-success "read-tree" "--reset" it (concat "--index-output=" #:file4)) (error "Cannot read tree %s" it))))) (if (file-remote-p default-directory) (let ((magit-tramp-process-environment (cons (concat "GIT_INDEX_FILE=" #:file4) magit-tramp-process-environment))) (if files (magit-call-git "add" "--" files) (let ((#:toplevel6 (magit-toplevel))) (if #:toplevel6 (let (...) (magit-call-git "add" "-u" ".")) (magit--not-inside-repository-error)))) (magit-git-string "write-tree")) (let ((process-environment (cons (concat "GIT_INDEX_FILE=" #:file4) process-environment))) (if files (magit-call-git "add" "--" files) (let ((#:toplevel7 (magit-toplevel))) (if #:toplevel7 (let (...) (magit-call-git "add" "-u" ".")) (magit--not-inside-repository-error)))) (magit-git-string "write-tree"))))
  (if #:toplevel5 (let ((default-directory #:toplevel5)) (let ((it parent)) (if it (progn (or (magit-git-success "read-tree" "--reset" it (concat "--index-output=" #:file4)) (error "Cannot read tree %s" it))))) (if (file-remote-p default-directory) (let ((magit-tramp-process-environment (cons (concat "GIT_INDEX_FILE=" #:file4) magit-tramp-process-environment))) (if files (magit-call-git "add" "--" files) (let ((#:toplevel6 ...)) (if #:toplevel6 (let ... ...) (magit--not-inside-repository-error)))) (magit-git-string "write-tree")) (let ((process-environment (cons (concat "GIT_INDEX_FILE=" #:file4) process-environment))) (if files (magit-call-git "add" "--" files) (let ((#:toplevel7 ...)) (if #:toplevel7 (let ... ...) (magit--not-inside-repository-error)))) (magit-git-string "write-tree")))) (magit--not-inside-repository-error))
  (let ((#:toplevel5 (magit-toplevel))) (if #:toplevel5 (let ((default-directory #:toplevel5)) (let ((it parent)) (if it (progn (or (magit-git-success "read-tree" "--reset" it ...) (error "Cannot read tree %s" it))))) (if (file-remote-p default-directory) (let ((magit-tramp-process-environment (cons ... magit-tramp-process-environment))) (if files (magit-call-git "add" "--" files) (let (...) (if #:toplevel6 ... ...))) (magit-git-string "write-tree")) (let ((process-environment (cons ... process-environment))) (if files (magit-call-git "add" "--" files) (let (...) (if #:toplevel7 ... ...))) (magit-git-string "write-tree")))) (magit--not-inside-repository-error)))
  (unwind-protect (let ((#:toplevel5 (magit-toplevel))) (if #:toplevel5 (let ((default-directory #:toplevel5)) (let ((it parent)) (if it (progn (or ... ...)))) (if (file-remote-p default-directory) (let ((magit-tramp-process-environment ...)) (if files (magit-call-git "add" "--" files) (let ... ...)) (magit-git-string "write-tree")) (let ((process-environment ...)) (if files (magit-call-git "add" "--" files) (let ... ...)) (magit-git-string "write-tree")))) (magit--not-inside-repository-error))) (condition-case nil (progn (delete-file (concat (file-remote-p default-directory) #:file4))) (error nil)))
  (let ((magit--refresh-cache nil) (#:file4 (magit-convert-filename-for-git (make-temp-name (magit-git-dir "index.magit."))))) (unwind-protect (let ((#:toplevel5 (magit-toplevel))) (if #:toplevel5 (let ((default-directory #:toplevel5)) (let ((it parent)) (if it (progn ...))) (if (file-remote-p default-directory) (let (...) (if files ... ...) (magit-git-string "write-tree")) (let (...) (if files ... ...) (magit-git-string "write-tree")))) (magit--not-inside-repository-error))) (condition-case nil (progn (delete-file (concat (file-remote-p default-directory) #:file4))) (error nil))))
  (let* ((wipref (magit--wip-wtree-ref ref)) (parent (magit-wip-get-parent ref wipref)) (tree (let ((magit--refresh-cache nil) (#:file4 (magit-convert-filename-for-git (make-temp-name ...)))) (unwind-protect (let ((#:toplevel5 ...)) (if #:toplevel5 (let ... ... ...) (magit--not-inside-repository-error))) (condition-case nil (progn (delete-file ...)) (error nil)))))) (magit-wip-update-wipref ref wipref tree parent files msg "worktree"))
  magit-wip-commit-worktree("refs/heads/master" (".gnu-emacs.el") "autosave .gnu-emacs.el after save")
  (let ((file (file-relative-name buffer-file-name))) (magit-wip-commit-worktree it (list file) (format (cond (msg) ((called-interactively-p 'any) "wip-save %s after save") (t "autosave %s after save")) file)))
  (let ((default-directory #:toplevel2)) (let ((file (file-relative-name buffer-file-name))) (magit-wip-commit-worktree it (list file) (format (cond (msg) ((called-interactively-p 'any) "wip-save %s after save") (t "autosave %s after save")) file))))
  (if #:toplevel2 (let ((default-directory #:toplevel2)) (let ((file (file-relative-name buffer-file-name))) (magit-wip-commit-worktree it (list file) (format (cond (msg) ((called-interactively-p ...) "wip-save %s after save") (t "autosave %s after save")) file)))) (magit--not-inside-repository-error))
  (let ((#:toplevel2 (magit-toplevel))) (if #:toplevel2 (let ((default-directory #:toplevel2)) (let ((file (file-relative-name buffer-file-name))) (magit-wip-commit-worktree it (list file) (format (cond (msg) (... "wip-save %s after save") (t "autosave %s after save")) file)))) (magit--not-inside-repository-error)))
  (progn (let ((#:toplevel2 (magit-toplevel))) (if #:toplevel2 (let ((default-directory #:toplevel2)) (let ((file (file-relative-name buffer-file-name))) (magit-wip-commit-worktree it (list file) (format (cond ... ... ...) file)))) (magit--not-inside-repository-error))))
  (if it (progn (let ((#:toplevel2 (magit-toplevel))) (if #:toplevel2 (let ((default-directory #:toplevel2)) (let ((file ...)) (magit-wip-commit-worktree it (list file) (format ... file)))) (magit--not-inside-repository-error)))))
  (let ((it (magit-wip-get-ref))) (if it (progn (let ((#:toplevel2 (magit-toplevel))) (if #:toplevel2 (let ((default-directory #:toplevel2)) (let (...) (magit-wip-commit-worktree it ... ...))) (magit--not-inside-repository-error))))))
  magit-wip-commit-buffer-file()
  run-hooks(after-save-hook)
  basic-save-buffer(nil)
  save-buffer()
```

I didn't investigate.  There were similar github issues in the past, but AFAICT this one is new.  Unless it's my fault, but I didn't change my config AFAIR.

TIA,

Michael.

**Comment by kyleam** [comment]
There haven't been any changes to the wip functionality recently.

Is this happening across all your Magit repositories, for one repository, or for a single branch in one repository?  If it's happening in a restricted manner, I think it's going to be tricky to get to the bottom of what caused the corrupted ref.

**Comment by jixiuf** [comment]
```
Debugger entered--Lisp error: (error "Cannot read tree refs/wip/wtree/refs/heads/font")
  signal(error ("Cannot read tree refs/wip/wtree/refs/heads/font"))
  error("Cannot read tree %s" "refs/wip/wtree/refs/heads/font")
  magit-wip-commit-worktree("refs/heads/font" ("vterm-module.c") " before stage")
  magit-wip-commit(("vterm-module.c") " before stage")
  magit-wip-commit-before-change(("vterm-module.c") " before stage")
  magit-stage-1("-u" ("vterm-module.c"))
  magit-stage(nil)
  funcall-interactively(magit-stage nil)
  call-interactively(magit-stage nil nil)
  command-execute(magit-stage)
```
I got this error when I do stage/unstage/  in the `font` branch ,and it only happening in my emacs-libvterm repositories I attached 
[emacs-libvterm.tar.gz](https://github.com/magit/magit/files/4157410/emacs-libvterm.tar.gz)

**Comment by kyleam** [comment]
@jixiuf Thanks for providing a repo where a read-tree error can be triggered.  In this case, here is how that read-tree call is failing:

```
% git read-tree --reset refs/wip/wtree/refs/heads/font --index-output=/tmp/magit.index.5
error: Entry 'CMakeLists.txt' not uptodate. Cannot merge
```

Tonight I don't have time to dig in and understand what's going, but I have a suspicion that we should be passing -i to read-tree:

```
       -i
           Usually a merge requires the index file as well as the files in the working tree to
           be up to date with the current head commit, in order not to lose local changes. This
           flag disables the check with the working tree and is meant to be used when creating
           a merge of trees that are not directly related to the current working tree status
           into a temporary index file.
```

```
% git read-tree -i --reset refs/wip/wtree/refs/heads/font --index-output=/tmp/magit.index.6
# no failure
```

**Comment by kyleam** [comment]
> Tonight I don't have time to dig in and understand what's going [...]

I've taken another look.  This is with the emacs-libvterm repo provided by @jixiuf, straight after extraction.  As mentioned above, this is how the read-tree call fails:

```
% git read-tree --reset refs/wip/wtree/refs/heads/font --index-output=.git/mg.tmp.index0                                                             
error: Entry 'CMakeLists.txt' not uptodate. Cannot merge
```

So the stat info from the index and the working tree are out of sync.

```
% git ls-files --debug CMakeLists.txt 
CMakeLists.txt                                              
  ctime: 1580575780:543605939
  mtime: 1580575780:543605939
  dev: 16777220	ino: 16111477
  uid: 501	gid: 20
  size: 1945	flags: 40004000
% stat --printf="%n\n  %Z\n  %Y\n  %d %i\n  %s\n" CMakeLists.txt CMakeLists.txt
  1581484115
  1580874081
  2053 9060856
  2325
```

Importantly, there are some flags set in the index.

```
% git ls-files -v CMakeLists.txt     
S CMakeLists.txt
```

So, this file has the "skip-worktree bit" set, and it looks like it did _not_ at some point within the current wip ref's lifetime:

```
% git log --oneline ..refs/wip/wtree/refs/heads/font -- CMakeLists.txt
5010516 autosave CMakeLists.txt after save
```

Like I said above, `read-tree -i` will get rid of the read-tree failures, but I'll need to explore/think about this a bit more before I have any confidence in a solution.

**Comment by kyleam** [comment]
I've started work on the skip-worktree related failure on the [km/wip-read-tree-skip-worktree][0] branch.  I should find time to finish that up tomorrow night.

[0]: https://github.com/magit/magit/compare/km/wip-read-tree-skip-worktree

**Comment by kyleam** [comment]
> I've started work on the skip-worktree related failure on the [km/wip-read-tree-skip-worktree](https://github.com/magit/magit/compare/km/wip-read-tree-skip-worktree) branch

I've pushed an update to that branch.  I'll plan to merge that in a couple of days unless there are objections.

**Comment by kyleam** [comment]
>  I'll plan to merge that in a couple of days unless there are objections.

Merged.

@michael-heerdegen  I have no idea if this is the cause of the failure you're seeing, but, lacking more information, I'm going to hope that it is.  If you still see failures with the latest master, please reopen.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> @michael-heerdegen I have no idea if this is the cause of the failure
> you're seeing, but, lacking more information, I'm going to hope that
> it is. If you still see failures with the latest master, please
> reopen.

Ok, thanks.  And your fix should make it work again without further
intervention from my side?

I currently have Magit 20200220.308 from Melpa, and the issue is still
present there.  Does that version include your fix?  Thanks, Michael.

**Comment by kyleam** [comment]
> Ok, thanks. And your fix should make it work again without further intervention from my side?

Yes, but if your files don't have skip-worktree or assume-unchanged bits (e.g., set through `magit-skip-worktree`), your issue is different than @jixiuf's and probably wouldn't be resolved by using `read-tree -i`.

> I currently have Magit 20200220.308 from Melpa, and the issue is still present there. Does that version include your fix?

Yes.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Yes, but if your files don't have skip-worktree or assume-unchanged
> bits (e.g., set through magit-skip-worktree), your issue is different
> than @jixiuf's and probably wouldn't be resolved by using read-tree
> -i.

What can I do to investigate from my side?

**Comment by michael-heerdegen** [comment]
Michael Heerdegen <michael_heerdegen@web.de> writes:

> What can I do to investigate from my side?

You had asked me if the error happens in every repository.  The answer
is "no".

**Comment by kyleam** [comment]
> What can I do to investigate from my side?

You could try calling

    git read-tree --index-output=tmp-index --reset refs/wip/wtree/refs/heads/<name of a failing branch>

and seeing what the error message is.

> You had asked me if the error happens in every repository. The answer is "no".

Is it a single repository?  A single branch in a single repository?

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> git read-tree --index-output=tmp-index --reset refs/wip/wtree/refs/heads/<name of a failing branch>
>
> and seeing what the error message is.

It says

| bash-5.0:micha:gnu-emacs$ git read-tree --index-output=tmp-index --reset 'refs/wip/wtree/refs/heads/master'
| fatal: Unable to create '/home/micha/gnu-emacs/.git/index.lock': File exists.

So I guess this is from a crash and I just have to remove the lock file?

> Is it a single repository? A single branch in a single repository?

If the answer still matters: Is "single" a technical term I don't know,
or do you mean if it is the only repo and branch where I see that?

Michael.

**Comment by kyleam** [comment]
> It says | bash-5.0:micha:gnu-emacs$ git read-tree --index-output=tmp-index --reset 'refs/wip/wtree/refs/heads/master' | fatal: Unable to create '/home/micha/gnu-emacs/.git/index.lock': File exists. So I guess this is from a crash and I just have to remove the lock file?

Yes, that'd be my guess.

>> Is it a single repository? A single branch in a single repository?
> If the answer still matters:

No, it probably doesn't matter given what I (think I) can infer from the info above but...

> Is "single" a technical term I don't know, or do you mean if it is the only repo and branch where I see that?

No, I wasn't using "single" in any particular technical sense, so perhaps the phrasing I chose is awkward/weird/region-specific.  You answered that it doesn't happen in every repository.  I was trying to get you to be more specific, wanting to know if it is just one particular repository where you're seeing this, and, if so, just when you're on one particular branch.  Given the error you show above, you wouldn't even have been able to check out another branch, so the "one particular branch" part is almost certainly irrelevant.

**Comment by kyleam** [comment]
Given we now know there was an index.lock file present, I'm going to close this, but please raise the issue again if you run into this situation again and think there's something Magit should be doing differently.

**Comment by michael-heerdegen** [comment]
Kyle Meyer <notifications@github.com> writes:

> Given we now know there was an index.lock file present, I'm going to
> close this,

Fine by me.  After removing the lock file everything works fine again.

> but please raise the issue again if you run into this situation again
> and think there's something Magit should be doing differently.

One thing: would it be ok to add "refs/wip" to the default value of
`magit-list-refs-namespaces`?

Thanks, Michael.

**Comment by tarsius** [comment]
> One thing: would it be ok to add "refs/wip" to the default value of `magit-list-refs-namespaces`?

I intentionally did not do that. Why do you think we should do that? (As far as I am concerned it is one of those "obscure refs that are not intended for human consumption" and that's the ones that don't get any special color to communicate special meaning to humans.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

>  One thing: would it be ok to add "refs/wip" to the default value of
>  magit-list-refs-namespaces?
>
> I intentionally did not do that. Why do you think we should do that?

For discoverability: that way it is listed for l o.  I'm open to any
other way to make the refs discoverable.  But it seems currently there
is no way to list wip commits unless you explicitly enter the path?

**Comment by tarsius** [comment]
> But it seems currently there is no way to list wip commits unless you explicitly enter the path?

The log transient features suffixes specifically for that: `l i` and `l w`.

They are shown if `magit-wip-mode` is enabled, but if you enabled the lower-level modes individually, then they currently are not. I'll fix that this evening.

**Comment by michael-heerdegen** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> They are shown if magit-wip-mode is enabled, but if you enabled the
> lower-level modes individually, then they currently are not. I'll fix
> that this evening.

Yes, I've indeed been using the lower level modes.  Maybe I'll just
switch to the new high-level mode.

Thanks, Michael.
